---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stefanma/public_html/
    - /bin/cp -R /home/stefanma/repositories/UTOR-MOD02-CHAL01-Developer-Website/assets $DEPLOYPATH
    - /bin/cp -R /home/stefanma/repositories/UTOR-MOD02-CHAL01-Developer-Website/index.html $DEPLOYPATH